### ISSUE TITLE
Störenfried Festung

### ISSUE THREAD

**Issue by plusterkopp** [tsosim/tsosim.github.io#3]
Wenn nur noch Bob und Alex drin sind, und ich mit 100S + 170K reingehe, sagt mir der Simulator max 49 verlorene Soldaten voraus. Tatsächlich gingen gerade alle Soldaten flöten, die Kanonen zum Glück nicht.

**Comment by tobster-de** [comment]
Du hast vermutlich die falsche Spalte abgelesen: Im "Maximum" fallen 49 S (maximaler Erfolg), aber im "Minimum" (minimaler Erfolg) fallen korrekt alle 100 S, wie von dir erfahren!

**Comment by plusterkopp** [comment]
oh :)
